### ISSUE TITLE
Docs: add recommended NATS server settings to use it as public from fronted

### ISSUE THREAD

**Issue by Lancetnik** [nats-io/nats.ws#231]
### Proposed change

Hello there! I am really **NATS** fan, but I am confused a bit about **NATS** public usage from frontend client.

All examples in your code are represents code-based authentication, but js code is storing in clients' browser. So, all users are able to use your site are able to connect to your **NATS** cluster as well. It seems a little bit undefended. 
TLS connection protects your channel, but it doesn't protect your cluster from undefined usage (like publishing to wrong subjects, wrong messages formats, DOS, etc).

I think, you have some server options to make such connections protected, but there is no any recommendations (and warnings about default settings usage) in **nats.ws** documentation. It will be really cool if you add notice about reccomended way to protect your cluster from public clients in project README (or link to the doc/article).

Thanks for your work!

### Use case

I want to use NATS right in my client app, but not sure about security.

**Comment by aricart** [comment]
For this you should be looking at the docs for nats-server - this is simply a client that works over websockets. 

See https://docs.nats.io/running-a-nats-service/configuration/websocket/websocket_conf

For the permissions, you have to craft those and set a topology that makes sense. Since NATS can isolate client traffic, the client authentication is going to determine what they can or not do. See https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt

You can also specify on the client and on the server to not gossip cluster updates, which means that the clients will only be able to connect to the URLs you have provided. See https://docs.nats.io/running-a-nats-service/configuration#configuration-properties `client_advertise`. 

You can even setup a cluster that only handles WS connections and then leafnodes.

But as you point out the security implications are important, and clients accessing from the open internet will need to be clamped down so they can only publish or subscribe to subjects that they should have access to.
